services:
  database:
    image: postgres:latest
    container_name: node-pg-migrate-test
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
      - "12345:5432"

